[package]
name = "ecosim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
winit = "0.27.5"
winapi = { version = "0.3.9", features = [
	"impl-default",
	"winuser",
	"wingdi",
	"sysinfoapi",
] }
raw-window-handle = "0.5.0"
raw-gl-context = "0.1.2"
sciter-rs = {version = "0.5.58", features = ["windowless"]}