[package]
name = "ecosim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.30.1"
winit = "0.27.5"
glow = "0.11.2"
egui_glow = "0.19.0"
image = "0.24.4"
rand = "0.8.5"


[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
