[package]
name = "ecosim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_glow = "0.19.0"
glow = "0.11.2"
image = "0.24.4"
rand = "0.8.5"

[dependencies.eframe]
version = "0.19.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
